version: '3'

services:
    frontend:
        container_name: frontend
        image: frontend:latest
        build:
            dockerfile: frontend.dockerfile
        ports:
            - '3000:3000'
        restart: always
        depends_on:
            backend:
                condition: service_healthy
