name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version # Verifiziert die Installation von pnpm

      - name: Verify pnpm Installation
        run: |
          if ! command -v pnpm &> /dev/null
          then
            echo "pnpm could not be found"
            exit 1
          fi

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build
        env:
          CI: true

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            const issue = context.issue;
            const message = `🚨 Build failed for commit [${context.sha}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}) on branch \`${context.ref}\`. Please check the [Actions tab](https://github.com/${context.repo.owner}/${context.repo.repo}/actions) for details.`;
            await github.issues.createComment({
              ...issue,
              body: message,
            });

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist # Angepasster Pfad zum Build-Output

