name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.11.0"
          cache: "pnpm"

      - name: Install pnpm
        run: |
          # Ensure pnpm is available (Netlify/GHA runners may already provide corepack)
          npm install -g pnpm
          pnpm --version # Verifies pnpm installation

      - name: Verify pnpm Installation
        run: |
          if ! command -v pnpm &> /dev/null
          then
            echo "pnpm could not be found"
            exit 1
          fi

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build
        env:
          CI: true

      - name: Notify on Failure (PR only)
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            // `github` and `context` are injected by the action
            const issue = context.issue;
            const message = `🚨 Build failed for commit [${context.sha}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}) on branch \`${context.ref}\`. Please check the [Actions tab](https://github.com/${context.repo.owner}/${context.repo.repo}/actions) for details.`;
            await github.issues.createComment({
              ...issue,
              body: message,
            });

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next # Upload Next.js build output
